#!/bin/sh
xelatex -synctex=1 -interaction=nonstopmode "\def\ThPrivateBuild{1} \input{thesis-paper.tex}"
biber thesis-paper
xelatex -synctex=1 -interaction=nonstopmode "\def\ThPrivateBuild{1} \input{thesis-paper.tex}"
